default:
  cluster: <%= ENV["ECS_CLUSTER"] %>
  runner: ecs
  region: ap-northeast-1
  container_definition:
    image: joker1007/wrapbox
    cpu: 256
    memory: 256
    essential: true
  # task_definition:
    # task_definition_name: task_def_name:154
    # main_container_name: container1

docker:
  runner: docker
  keep_container: false
  container_definition:
    image: joker1007/wrapbox
    cpu: 600
    memory: 1024

ecs_with_launch_template:
  cluster: <%= ENV["ECS_CLUSTER"] %>
  runner: ecs
  region: ap-northeast-1
  container_definition:
    image: joker1007/wrapbox
    cpu: 256
    memory: 256
    essential: true
  launch_instances:
    launch_template:
      launch_template_id: <%= ENV["LAUNCH_TEMPLATE_ID"] %>
      version: $Latest
    tag_specifications:
      - resource_type: instance
        tags:
          - key: Purpose
            value: wrapbox_spec
    wait_until_instance_terminated: false

ecs_without_runner:
  cluster: <%= ENV["ECS_CLUSTER"] %>
  region: ap-northeast-1
  container_definition:
    image: joker1007/wrapbox
    cpu: 256
    memory: 256
    essential: true
